default: &default
  adapter: postgresql
  template: template0
  encoding: unicode
  collation: en_US.UTF-8
  pool: 5
  timeout: 5000
  sslmode: disable
  reaping_frequency: 10

production:
  <<: *default
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: nigh_cage_production
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: night_cage_development
  host: localhost
  username: postgres
  password: postgres

test: &test
  <<: *default
  database: night_cage_test
  username: postgres
  password: postgres
